# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 218)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(625, 218))
        MainWindow.setMaximumSize(QtCore.QSize(625, 218))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_autologin_onConnectionLoss = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autologin_onConnectionLoss.setGeometry(QtCore.QRect(450, 30, 171, 17))
        self.checkBox_autologin_onConnectionLoss.setObjectName("checkBox_autologin_onConnectionLoss")
        self.checkBox_save = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_save.setGeometry(QtCore.QRect(240, 30, 101, 17))
        self.checkBox_save.setObjectName("checkBox_save")
        self.lineEdit_auto = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_auto.setGeometry(QtCore.QRect(350, 10, 31, 20))
        self.lineEdit_auto.setObjectName("lineEdit_auto")
        self.textArea_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textArea_log.setGeometry(QtCore.QRect(240, 60, 371, 131))
        self.textArea_log.setObjectName("textArea_log")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pass.setGeometry(QtCore.QRect(70, 50, 131, 20))
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.label_id.setObjectName("label_id")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(30, 80, 81, 31))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(20, 49, 51, 21))
        self.label_pass.setObjectName("label_pass")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(120, 80, 81, 31))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(70, 20, 131, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.checkBox_auto = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_auto.setGeometry(QtCore.QRect(240, 10, 101, 17))
        self.checkBox_auto.setObjectName("checkBox_auto")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 51, 21))
        self.label.setObjectName("label")
        self.checkBox_fileLogging = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_fileLogging.setGeometry(QtCore.QRect(450, 10, 111, 17))
        self.checkBox_fileLogging.setObjectName("checkBox_fileLogging")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_id, self.lineEdit_pass)
        MainWindow.setTabOrder(self.lineEdit_pass, self.pushButton_login)
        MainWindow.setTabOrder(self.pushButton_login, self.pushButton_logout)
        MainWindow.setTabOrder(self.pushButton_logout, self.checkBox_auto)
        MainWindow.setTabOrder(self.checkBox_auto, self.lineEdit_auto)
        MainWindow.setTabOrder(self.lineEdit_auto, self.checkBox_save)
        MainWindow.setTabOrder(self.checkBox_save, self.textArea_log)
        MainWindow.setTabOrder(self.textArea_log, self.checkBox_autologin_onConnectionLoss)
        MainWindow.setTabOrder(self.checkBox_autologin_onConnectionLoss, self.checkBox_fileLogging)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RubLogin"))
        self.checkBox_autologin_onConnectionLoss.setText(_translate("MainWindow", "Auto login on connection loss"))
        self.checkBox_save.setText(_translate("MainWindow", "Save user data"))
        self.lineEdit_auto.setText(_translate("MainWindow", "30"))
        self.label_id.setText(_translate("MainWindow", "LoginID"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label_pass.setText(_translate("MainWindow", "Password"))
        self.pushButton_logout.setText(_translate("MainWindow", "Logout"))
        self.checkBox_auto.setText(_translate("MainWindow", "Auto login every"))
        self.label.setText(_translate("MainWindow", "minutes"))
        self.checkBox_fileLogging.setText(_translate("MainWindow", "Write log to file"))

